### ISSUE TITLE
Issue with `torch.bmm` and `BFloat16` tensors

### ISSUE THREAD

**Issue by ramyologist** [ad-freiburg/whitespace-correction#4]
Hello! First off, I'd like to express my appreciation for the work you've done on the `whitespace-correction` tool. It's been very useful, but I've encountered a minor issue.

While trying out the tool with the command `wsc -p splitthissentenceforme`, I faced a `RuntimeError` associated with the `torch.bmm` function. The error message indicates that batch matrix multiplication isn't currently supported for tensors of the `BFloat16` data type.

Here's the specific error for clarity:

Traceback (most recent call last):
  File "/home/r/PycharmProjects/whitespace-correction/venv/bin/wsc", line 8, in <module>
    sys.exit(main())
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/whitespace_correction/api/cli.py", line 64, in main
    WhitespaceCorrectionCli(parser.parse_args()).run()
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/text_utils/api/cli.py", line 320, in run
    opt = next(self.process_iter(self.cor, iter([ipt])))
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/whitespace_correction/api/cli.py", line 26, in process_iter
    yield from processor.correct_iter(
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/whitespace_correction/api/corrector.py", line 425, in correct_iter
    output = self._process_sorted(
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/text_utils/api/processor.py", line 303, in _process_sorted
    outputs = self._run_model(batch)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/text_utils/api/processor.py", line 203, in _run_model
    outputs = self._inference(inputs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/whitespace_correction/api/corrector.py", line 184, in _inference
    outputs, _ = self.model(**inputs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/whitespace_correction/model.py", line 63, in forward
    enc, kwargs = self.encoder(emb, pos=pos_emb, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/text_utils/modules/encoder.py", line 369, in forward
    pos, _ = self.grouping(pos, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/r/PycharmProjects/whitespace-correction/venv/lib/python3.10/site-packages/text_utils/modules/grouping.py", line 41, in forward
    result = torch.bmm(weights, feats)
RuntimeError: "bmm_sparse_dense" not implemented for 'BFloat16'

Thanks for considering this issue - I appreciate any guidance or fixes you can provide!

**Comment by bastiscode** [comment]
That is because you used CPU instead GPU for inference, and for the byte-based models we use sparse matrix multiplication internally which is not implemented for bfp16 on CPU. Of course this should not raise an error to the user who just wants to run our models on CPU. 
I just released new versions of text-utils and whitespace-correction (v0.2.2 and v0.2.1 respectively) that should fix this. So just upgrade with `pip install -U whitespace-correction`. By default the pretrained whitespace correction models will be run with fp32 precision on CPU now and you should not get an error anymore. On GPU the models are still run with fp16 precision by default and should work as before.
